language: scala
sudo: false
scala:
- 2.10.6

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
- sbt -J-Xmx3000M ++$TRAVIS_SCALA_VERSION compile
# Tricks to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

deploy:
  provider: releases
  api_key:
    secure: ZHv5KXgAHNvO6ZS2cv5SdQ43UMjcc1Bm7p9Q66z4NJoLNq5SY/Ln9ZFeUgoBMv+1SPvzL0GRWLxBxa4UYuFgFwRywlU8hQ1GF0ztZ35bvZUrFvTWp4sM62sdmSogHFDmgpG58IPNeQSPcZ+sYFhlWzvAz9hUCXzPPu6jeZSanew=
  file: scalapbc/target/universal/scalapbc-${TRAVIS_TAG:1}.zip
  skip_cleanup: true
  on:
    repo: trueaccord/ScalaPB
    tags: true
    scala: 2.11.7

