language: scala
sudo: required
dist: trusty

scala:
- 2.12.2

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/boot/

script:
- if [[ $TRAVIS_SCALA_VERSION != 2.10.* ]]; then ./e2e.sh; fi
- cd examples && sbt test && cd ..
- sbt -J-Xmx4500M ++$TRAVIS_SCALA_VERSION test
- sbt -J-Xmx4500M ++$TRAVIS_SCALA_VERSION universal:packageBin

- ./test_generated_code_checked_in.sh

# Tricks to avoid unnecessary cache updates
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

matrix:
  include:
  - dist: trusty
    group: edge
    sudo: required
    scala: 2.12.2
    jdk: oraclejdk9
    script:
    # https://github.com/sbt/sbt/pull/2951
    - git clone https://github.com/retronym/java9-rt-export
    - cd java9-rt-export/
    - git checkout 1019a2873d057dd7214f4135e84283695728395d
    - jdk_switcher use oraclejdk8
    - sbt package
    - jdk_switcher use oraclejdk9
    - mkdir -p $HOME/.sbt/0.13/java9-rt-ext; java -jar target/java9-rt-export-*.jar $HOME/.sbt/0.13/java9-rt-ext/rt.jar
    - jar tf $HOME/.sbt/0.13/java9-rt-ext/rt.jar | grep java/lang/Object
    - cd ..
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/9ade5fa54914ca8aded44105bf4b9a60966f3ccd/sbt && chmod +x ./sbt
    - ./e2e.sh
    - cd examples && ../sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext test && cd ..
    - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext -J-Xmx4500M ++$TRAVIS_SCALA_VERSION test
    - ./sbt -Dscala.ext.dirs=$HOME/.sbt/0.13/java9-rt-ext -J-Xmx4500M ++$TRAVIS_SCALA_VERSION universal:packageBin
    # Tricks to avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
