language: scala
sudo: required
dist: trusty

scala:
- 2.10.6
- 2.11.12
- 2.12.2

env:
- TEST_SCRIPT=e2e.sh E2E_SHADED=1

matrix:

# These directories are cached to S3 at the end of the build
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt

script:
- ./$TEST_SCRIPT

before_cache:
# Tricks to avoid unnecessary cache updates
- find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
- find $HOME/.sbt -name "*.lock" -print -delete
